const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');

const app = express();
const PORT = 80;

app.use(cors());
app.use(express.json());

// Helper to determine OS and paths
const isLinux = os.platform() === 'linux';
const interfacesPath = isLinux ? '/etc/network/interfaces' : path.join(__dirname, '..', 'config_data', 'interfaces_mock.txt');
const dnsmasqPath = isLinux ? '/etc/dnsmasq.d/scada.conf' : path.join(__dirname, '..', 'config_data', 'dnsmasq_mock.conf');
const wpaSupplicantPath = isLinux ? '/etc/wpa_supplicant/wpa_supplicant.conf' : path.join(__dirname, '..', 'config_data', 'wpa_supplicant_mock.conf');

// Ensure config_data directory exists (on ALL platforms)
const configDataDir = path.join(__dirname, '..', 'config_data');
if (!fs.existsSync(configDataDir)) fs.mkdirSync(configDataDir, { recursive: true });

// Ensure default network configuration exists (First boot initialization)
if (!fs.existsSync(dnsmasqPath)) {
  fs.writeFileSync(dnsmasqPath, 'interface=eth1\ndhcp-range=eth1,170.0.0.2,170.0.0.100,255.255.255.0,24h\ndhcp-option=eth1,6,8.8.8.8\n');
  if (isLinux) { try { execSync('systemctl restart dnsmasq'); } catch(e) {} }
}

const interfacesHeader = '# Auto-generated by SCADA Gateway';
let interfacesContent = fs.existsSync(interfacesPath) ? fs.readFileSync(interfacesPath, 'utf-8') : '';

// If the file is not managed by us yet, forcefully rewrite it to our defaults
if (!interfacesContent.includes(interfacesHeader)) {
  interfacesContent = `${interfacesHeader}\nauto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp\n\nauto eth1\niface eth1 inet static\n  address 170.0.0.1\n  netmask 255.255.255.0\n\n# Fallback Virtual IP for Rescue\nauto eth1:0\niface eth1:0 inet static\n  address 10.10.10.254\n  netmask 255.255.255.0\n\nauto wlan0\niface wlan0 inet dhcp\n  wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf\n`;
  fs.writeFileSync(interfacesPath, interfacesContent);
  if (isLinux) { try { execSync('systemctl restart networking'); } catch(e) {} }
}

// Auth
const authFilePath = path.join(__dirname, '..', 'config_data', 'auth.json');
if (!fs.existsSync(authFilePath)) {
  fs.writeFileSync(authFilePath, JSON.stringify({ username: 'admin', password: 'admin' }, null, 2));
}

app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body;
  try {
    const auth = JSON.parse(fs.readFileSync(authFilePath, 'utf-8'));
    if (username === auth.username && password === auth.password) {
      res.json({ token: 'fake-jwt-token-123', username: auth.username });
    } else {
      res.status(401).json({ error: 'Invalid credentials' });
    }
  } catch(e) {
    res.status(500).json({ error: 'Auth error' });
  }
});

app.post('/api/auth/change-password', (req, res) => {
  const { currentPassword, newPassword } = req.body;
  try {
    const auth = JSON.parse(fs.readFileSync(authFilePath, 'utf-8'));
    if (currentPassword !== auth.password) {
      return res.status(401).json({ error: 'Current password is incorrect' });
    }
    auth.password = newPassword;
    fs.writeFileSync(authFilePath, JSON.stringify(auth, null, 2));
    res.json({ success: true, message: 'Password changed successfully' });
  } catch(e) {
    res.status(500).json({ error: 'Failed to change password' });
  }
});

// Network API (WAN: eth0, LAN: eth1)
const getNetworkConfig = () => {
  const nets = os.networkInterfaces();
  
  let wanConfig = {
    mode: 'DHCP', dnsMode: 'Auto', dns1: '8.8.8.8', dns2: '8.8.4.4', mtu: '1500',
    staticIp: '', netmask: '255.255.255.0', gateway: '', mac: '', status: 'Disconnected'
  };
  let lanConfig = {
    ip: '170.0.0.1',
    netmask: '255.255.255.0',
    dhcpEnabled: false,
    dhcpStart: '',
    dhcpEnd: '',
    leaseTime: 1440,
    dns: '8.8.8.8',
    staticHosts: [],
    dhcpHosts: []
  };
  let wlanConfig = {
    enabled: false, mode: 'DHCP', ssid: '', password: '', staticIp: '', netmask: '255.255.255.0', gateway: '', mac: '', status: 'Disconnected'
  };

  // 1. Parse /etc/network/interfaces
  try {
    if (fs.existsSync(interfacesPath)) {
      const ifaces = fs.readFileSync(interfacesPath, 'utf-8');
      
      const eth0BlockMatch = ifaces.match(/iface eth0 inet static[\s\S]*?(?=iface|$)/);
      if (eth0BlockMatch) {
        wanConfig.mode = 'Static IP';
        wanConfig.dnsMode = 'Manual';
        const block = eth0BlockMatch[0];
        const getVal = (key) => { const m = block.match(new RegExp(`^\\s*${key}\\s+(.+)`, 'm')); return m ? m[1].trim() : ''; };
        wanConfig.staticIp = getVal('address');
        wanConfig.netmask = getVal('netmask') || '255.255.255.0';
        wanConfig.gateway = getVal('gateway');
        wanConfig.mtu = getVal('mtu') || '1500';
        const dns = getVal('dns-nameservers');
        if (dns) {
          const dnsParts = dns.split(/\s+/);
          if(dnsParts[0]) wanConfig.dns1 = dnsParts[0];
          if(dnsParts[1]) wanConfig.dns2 = dnsParts[1];
        }
      }

      const eth1BlockMatch = ifaces.match(/iface eth1 inet static[\s\S]*?(?=iface|$)/);
      if (eth1BlockMatch) {
        const block = eth1BlockMatch[0];
        const getVal = (key) => { const m = block.match(new RegExp(`^\\s*${key}\\s+(.+)`, 'm')); return m ? m[1].trim() : ''; };
        lanConfig.ip = getVal('address') || '170.0.0.1';
        lanConfig.netmask = getVal('netmask') || '255.255.255.0';
      }

      const wlan0BlockMatch = ifaces.match(/iface wlan0 inet static[\s\S]*?(?=iface|$)/);
      if (wlan0BlockMatch) {
        wlanConfig.mode = 'Static IP';
        const block = wlan0BlockMatch[0];
        const getVal = (key) => { const m = block.match(new RegExp(`^\\s*${key}\\s+(.+)`, 'm')); return m ? m[1].trim() : ''; };
        wlanConfig.staticIp = getVal('address');
        wlanConfig.netmask = getVal('netmask') || '255.255.255.0';
        wlanConfig.gateway = getVal('gateway');
      }
      if (ifaces.includes('iface wlan0 inet')) {
        wlanConfig.enabled = true;
      }
    }
  } catch(e) { console.error("Error reading interfaces:", e); }

  // Parse wpa_supplicant.conf
  try {
    if (fs.existsSync(wpaSupplicantPath)) {
      const wpaConf = fs.readFileSync(wpaSupplicantPath, 'utf-8');
      const ssidMatch = wpaConf.match(/ssid="([^"]+)"/);
      const pskMatch = wpaConf.match(/psk="([^"]+)"/);
      if (ssidMatch) wlanConfig.ssid = ssidMatch[1];
      if (pskMatch) wlanConfig.password = pskMatch[1];
    }
  } catch(e) { console.error("Error reading wpa_supplicant:", e); }

  // 2. Parse dnsmasq config for LAN DHCP
  try {
    if (fs.existsSync(dnsmasqPath)) {
      const dnsmasqContent = fs.readFileSync(dnsmasqPath, 'utf-8');
      if (dnsmasqContent.includes('interface=eth1')) lanConfig.dhcpEnabled = true;
      const lines = dnsmasqContent.split('\n');
      lines.forEach(line => {
        if (line.trim().startsWith('dhcp-range=eth1')) {
          const parts = line.split('=')[1].split(',');
          lanConfig.dhcpStart = parts[1] || '';
          lanConfig.dhcpEnd = parts[2] || '';
        }
        if (line.trim().startsWith('dhcp-option=eth1,6,')) {
          lanConfig.dns = line.split(',').pop().trim();
        }
        if (line.trim().startsWith('dhcp-host=')) {
          const parts = line.split('=')[1].split(',');
          if (parts.length >= 2) {
            lanConfig.staticHosts.push({
              mac: parts[0] || '',
              ip: parts[1] || '',
              hostname: parts[2] || ''
            });
          }
        }
      });
    }
    
    // Parse dnsmasq.leases for dynamic hosts
    const leasesPath = '/var/lib/misc/dnsmasq.leases';
    if (fs.existsSync(leasesPath)) {
      const leasesContent = fs.readFileSync(leasesPath, 'utf-8');
      leasesContent.split('\n').forEach(line => {
        const parts = line.trim().split(/\s+/);
        if (parts.length >= 4) {
          const expiresAt = parseInt(parts[0]) * 1000; // js uses ms
          lanConfig.dhcpHosts.push({
            mac: parts[1],
            ip: parts[2],
            hostname: parts[3] === '*' ? '--' : parts[3],
            leaseTime: isNaN(expiresAt) ? '--' : new Date(expiresAt).toLocaleString()
          });
        }
      });
    }

  } catch (e) { console.error("Error reading dnsmasq:", e); }

  // 3. Map live network interfaces (MAC and Live IP)
  const mapLive = (ethName, conf) => {
    if (nets[ethName] && nets[ethName].length > 0) {
      conf.mac = nets[ethName][0].mac;
      const ipv4 = nets[ethName].find(n => n.family === 'IPv4' || n.family === 4);
      if (ipv4) {
        conf.liveIp = ipv4.address;
        conf.liveNetmask = ipv4.netmask;
        conf.status = 'Connected';
      }
    }
    // Fallback: Read MAC from sysfs if interface is down and missing from os.networkInterfaces
    if ((!conf.mac || conf.mac === '--') && isLinux) {
      try {
        const mac = fs.readFileSync(`/sys/class/net/${ethName}/address`, 'utf-8').trim();
        if (mac) conf.mac = mac;
      } catch(e) {}
    }
  };
  mapLive('eth0', wanConfig);
  mapLive('eth1', lanConfig);
  mapLive('wlan0', wlanConfig);

  // 4. Try getting live gateway for WAN
  if (isLinux) {
    try {
      const gw = execSync("ip route show default dev eth0 | awk '{print $3}'").toString().trim();
      if (gw) wanConfig.liveGateway = gw;
    } catch(e) {}
  }

  // 5. Read /proc/net/dev for RX/TX bytes and connection uptime
  const formatBytes = (bytes) => {
    const b = parseInt(bytes) || 0;
    if (b >= 1024 * 1024) return `${(b / 1024 / 1024).toFixed(1)} MB`;
    if (b >= 1024) return `${(b / 1024).toFixed(1)} KB`;
    return `${b} B`;
  };

  const getConnTime = (iface) => {
    // Reads carrier_up_count + operstate to estimate time online
    // Fallback: use system uptime as max bound
    if (!isLinux) return '--';
    try {
      const state = fs.readFileSync(`/sys/class/net/${iface}/operstate`, 'utf-8').trim();
      if (state !== 'up') return 'Disconnected';
      // Read uptime in seconds
      const uptime = parseFloat(fs.readFileSync('/proc/uptime', 'utf-8').split(' ')[0]);
      const h = Math.floor(uptime / 3600).toString().padStart(2, '0');
      const m = Math.floor((uptime % 3600) / 60).toString().padStart(2, '0');
      const s = Math.floor(uptime % 60).toString().padStart(2, '0');
      return `${h}:${m}:${s}`;
    } catch(e) { return '--'; }
  };

  if (isLinux) {
    try {
      const netDev = fs.readFileSync('/proc/net/dev', 'utf-8');
      netDev.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed.startsWith('eth0:')) {
          const parts = trimmed.replace('eth0:', '').trim().split(/\s+/);
          wanConfig.receive = formatBytes(parts[0]);  // RX bytes
          wanConfig.send = formatBytes(parts[8]);     // TX bytes
        }
        if (trimmed.startsWith('eth1:')) {
          const parts = trimmed.replace('eth1:', '').trim().split(/\s+/);
          lanConfig.receive = formatBytes(parts[0]);
          lanConfig.send = formatBytes(parts[8]);
        }
        if (trimmed.startsWith('wlan0:')) {
          const parts = trimmed.replace('wlan0:', '').trim().split(/\s+/);
          wlanConfig.receive = formatBytes(parts[0]);
          wlanConfig.send = formatBytes(parts[8]);
        }
      });
    } catch(e) {}
    wanConfig.connTime = getConnTime('eth0');
    lanConfig.connTime = getConnTime('eth1');
    wlanConfig.connTime = getConnTime('wlan0');
  }

  return { wan: wanConfig, lan: lanConfig, wlan: wlanConfig };
};

app.get('/api/network', (req, res) => {
  res.json(getNetworkConfig());
});

app.post('/api/network', (req, res) => {
  const { wan, lan } = req.body;
  const currentConfig = getNetworkConfig();
  const wanToSave = wan || currentConfig.wan;
  const lanToSave = lan || currentConfig.lan;
  
  try {
    // 1. Generate /etc/network/interfaces content
    let interfacesContent = `# Auto-generated by SCADA Gateway\nauto lo\niface lo inet loopback\n\n`;
    
    // WAN
    if (wanToSave) {
      interfacesContent += `auto eth0\n`;
      if (wanToSave.mode === 'DHCP') {
        interfacesContent += `iface eth0 inet dhcp\n`;
      } else {
        interfacesContent += `iface eth0 inet static\n`;
        interfacesContent += `  address ${wanToSave.staticIp}\n`;
        interfacesContent += `  netmask ${wanToSave.netmask}\n`;
        if (wanToSave.gateway) interfacesContent += `  gateway ${wanToSave.gateway}\n`;
        if (wanToSave.dnsMode === 'Manual' && (wanToSave.dns1 || wanToSave.dns2)) {
           let dnsLine = `  dns-nameservers`;
           if (wanToSave.dns1) dnsLine += ` ${wanToSave.dns1}`;
           if (wanToSave.dns2) dnsLine += ` ${wanToSave.dns2}`;
           interfacesContent += dnsLine + `\n`;
        }
      }
      if (wanToSave.mtu) interfacesContent += `  mtu ${wanToSave.mtu}\n`;
      interfacesContent += `\n`;
    }

    // LAN
    if (lanToSave) {
      interfacesContent += `auto eth1\n`;
      interfacesContent += `iface eth1 inet static\n`;
      interfacesContent += `  address ${lanToSave.ip}\n`;
      interfacesContent += `  netmask ${lanToSave.netmask}\n\n`;
      interfacesContent += `# Fallback Virtual IP for Rescue\n`;
      interfacesContent += `auto eth1:0\n`;
      interfacesContent += `iface eth1:0 inet static\n`;
      interfacesContent += `  address 10.10.10.254\n`;
      interfacesContent += `  netmask 255.255.255.0\n\n`;
    }

    // WLAN
    const wlanToSave = req.body.wlan || currentConfig.wlan;
      if (wlanToSave && wlanToSave.enabled) {
        interfacesContent += `auto wlan0\niface wlan0 inet ${wlanToSave.mode === 'Static IP' ? 'static' : 'dhcp'}\n`;
        if (wlanToSave.mode === 'Static IP') {
          if (wlanToSave.staticIp) interfacesContent += `  address ${wlanToSave.staticIp}\n`;
          if (wlanToSave.netmask) interfacesContent += `  netmask ${wlanToSave.netmask}\n`;
          if (wlanToSave.gateway) interfacesContent += `  gateway ${wlanToSave.gateway}\n`;
        }
        interfacesContent += `  wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf\n\n`;
      }
      // Update wpa_supplicant.conf
      let wpaConf = `ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\nupdate_config=1\ncountry=US\n\n`;
      if (wlanToSave.ssid) {
        wpaConf += `network={\n  ssid="${wlanToSave.ssid}"\n`;
        if (wlanToSave.password) {
          wpaConf += `  psk="${wlanToSave.password}"\n`;
        } else {
          wpaConf += `  key_mgmt=NONE\n`;
        }
        wpaConf += `}\n`;
      }
      fs.writeFileSync(wpaSupplicantPath, wpaConf);

    fs.writeFileSync(interfacesPath, interfacesContent);

    // 2. Generate dnsmasq config for LAN DHCP
    if (lanToSave) {
      let dnsmasqContent = '';
      if (lanToSave.dhcpEnabled) {
        dnsmasqContent += `interface=eth1\n`;
        dnsmasqContent += `dhcp-range=eth1,${lanToSave.dhcpStart},${lanToSave.dhcpEnd},${lanToSave.netmask},${lanToSave.leaseTime}m\n`;
        if (lanToSave.dns) {
          dnsmasqContent += `dhcp-option=eth1,6,${lanToSave.dns}\n`;
        }
        if (lanToSave.staticHosts && lanToSave.staticHosts.length > 0) {
          lanToSave.staticHosts.forEach(host => {
            if (host.mac && host.ip) {
              const hostname = host.hostname || '*';
              dnsmasqContent += `dhcp-host=${host.mac},${host.ip},${hostname}\n`;
            }
          });
        }
      }
      fs.writeFileSync(dnsmasqPath, dnsmasqContent);
    }

    res.json({ success: true, message: 'Network configuration updated successfully!' });

    // 3. Restart services asynchronously so the response reaches the client first
    if (isLinux) {
      setTimeout(() => {
        console.log('Restarting networking and dnsmasq...');
        try { execSync('systemctl restart dnsmasq'); } catch(e) {}
        try { execSync('ifdown -a'); } catch(e) {}
        try { execSync('killall wpa_supplicant'); } catch(e) {}
        try { execSync('rm -rf /var/run/wpa_supplicant/wlan0'); } catch(e) {}
        try { execSync('rfkill unblock wlan'); } catch(e) {}
        try { execSync('systemctl restart networking'); } catch(e) {}
      }, 1000);
    }
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to apply network configuration', details: error.message });
  }
});

// System Time API
const timesyncdPath = isLinux ? '/etc/systemd/timesyncd.conf' : path.join(__dirname, '..', 'config_data', 'timesyncd_mock.conf');
if (!isLinux && !fs.existsSync(timesyncdPath)) {
  fs.writeFileSync(timesyncdPath, '[Time]\nNTP=ntp.aliyun.com ntp.gwadar.cn\n');
}
app.get('/api/network/routing', (req, res) => {
  let routes = [];
  if (isLinux) {
    try {
      const output = execSync('ip route').toString().trim();
      const lines = output.split('\n');
      routes = lines.map(line => {
        const parts = line.trim().split(/\s+/);
        // Default format: default via 192.168.1.1 dev eth0 src 192.168.1.10 metric 202
        // Subnet format: 192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.10 metric 202
        let target = parts[0];
        let gateway = '0.0.0.0';
        let netmask = '255.255.255.255';
        let flags = 'U';
        let iface = '';
        let metric = '0';
        
        if (target === 'default') {
          target = '0.0.0.0';
          netmask = '0.0.0.0';
          flags = 'UG';
        } else if (target.includes('/')) {
          const [ip, cidr] = target.split('/');
          target = ip;
          // approximate netmask from cidr
          const maskBits = parseInt(cidr, 10);
          const mask = ~((1 << (32 - maskBits)) - 1) >>> 0;
          netmask = [ (mask >>> 24) & 255, (mask >>> 16) & 255, (mask >>> 8) & 255, mask & 255 ].join('.');
        }

        const viaIdx = parts.indexOf('via');
        if (viaIdx !== -1) gateway = parts[viaIdx + 1];

        const devIdx = parts.indexOf('dev');
        if (devIdx !== -1) iface = parts[devIdx + 1];

        const metricIdx = parts.indexOf('metric');
        if (metricIdx !== -1) metric = parts[metricIdx + 1];

        return {
          target,
          gateway,
          netmask,
          flag: flags,
          metric,
          ref: '0',
          use: '0',
          interface: iface
        };
      });
    } catch(e) {
      console.error("Error reading routing table:", e);
    }
  } else {
    // Mock for Windows dev
    routes = [
      { target: '0.0.0.0', gateway: '192.168.1.1', netmask: '0.0.0.0', flag: 'UG', metric: '0', ref: '0', use: '0', interface: 'eth0' },
      { target: '192.168.1.0', gateway: '0.0.0.0', netmask: '255.255.255.0', flag: 'U', metric: '0', ref: '0', use: '0', interface: 'eth0' },
      { target: '192.168.30.0', gateway: '0.0.0.0', netmask: '255.255.255.0', flag: 'U', metric: '0', ref: '0', use: '0', interface: 'eth1' }
    ];
  }
  res.json({ routes });
});
app.get('/api/system/time', (req, res) => {
  let config = {
    timeZone: 'UTC',
    ntpEnabled: true,
    ntpServer1: 'ntp.aliyun.com',
    ntpServer2: 'ntp.gwadar.cn',
    deviceTime: new Date().toISOString()
  };

  try {
    if (isLinux) {
      try { config.timeZone = execSync("cat /etc/timezone").toString().trim(); } catch(e){}
      try { 
        const ntpStatus = execSync("timedatectl show --property=NTP").toString().trim();
        config.ntpEnabled = ntpStatus.includes('yes');
      } catch(e){}
    }
    if (fs.existsSync(timesyncdPath)) {
      const timesyncdContent = fs.readFileSync(timesyncdPath, 'utf-8');
      const match = timesyncdContent.match(/^NTP=(.*)$/m);
      if (match && match[1]) {
        const servers = match[1].trim().split(/\s+/);
        config.ntpServer1 = servers[0] || '';
        config.ntpServer2 = servers[1] || '';
      }
    }
  } catch (e) { console.error("Error reading time config:", e); }

  config.deviceTime = new Date().toLocaleString('sv').replace('T', ' ');
  res.json(config);
});

app.post('/api/system/time', (req, res) => {
  const { action, payload } = req.body;
  try {
    if (action === 'apply_ntp') {
      const { ntpEnabled, ntpServer1, ntpServer2 } = payload;
      let timesyncdContent = `[Time]\n`;
      let servers = [];
      if (ntpServer1) servers.push(ntpServer1);
      if (ntpServer2) servers.push(ntpServer2);
      if (servers.length > 0) {
        timesyncdContent += `NTP=${servers.join(' ')}\n`;
      }
      fs.writeFileSync(timesyncdPath, timesyncdContent);
      
      if (isLinux) {
        try { execSync(`timedatectl set-ntp ${ntpEnabled ? 'true' : 'false'}`); } catch(e){}
        if (ntpEnabled) {
          try { execSync('systemctl restart systemd-timesyncd'); } catch(e){}
        }
      }
    } else if (action === 'set_time') {
      const { dateTime } = payload;
      if (isLinux && dateTime) {
        try { execSync(`timedatectl set-ntp false`); } catch(e){} // must disable ntp to set time manually
        try { execSync(`date -s "${dateTime}"`); } catch(e){}
        try { execSync(`hwclock -w`); } catch(e){} // save to RTC if available
      }
    } else if (action === 'set_timezone') {
      const { timeZone } = payload;
      if (isLinux && timeZone) {
        try { execSync(`timedatectl set-timezone "${timeZone}"`); } catch(e){}
      }
    }
    res.json({ success: true, message: 'Time configuration updated' });
  } catch(error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to apply time configuration', details: error.message });
  }
});

// Edge Computing JSON Storage API
app.get('/api/edge/:type', (req, res) => {
  const type = req.params.type;
  const filePath = path.join(__dirname, '..', 'config_data', `${type}.json`);
  if (fs.existsSync(filePath)) {
    try {
      res.json(JSON.parse(fs.readFileSync(filePath, 'utf-8')));
    } catch (e) { res.json({ slaves: [], points: [] }); }
  } else {
    res.json({ slaves: [], points: [] });
  }
});

app.post('/api/edge/:type', (req, res) => {
  const type = req.params.type;
  const filePath = path.join(__dirname, '..', 'config_data', `${type}.json`);
  try {
    fs.writeFileSync(filePath, JSON.stringify(req.body, null, 2));
    res.json({ success: true, message: 'Configuration saved' });
  } catch (e) {
    res.status(500).json({ error: 'Failed to save configuration' });
  }
});



// System Management API (Reboot)
app.post('/api/system/reboot', (req, res) => {
  try {
    if (isLinux) {
      console.log("Rebooting system...");
      execSync('reboot');
    }
    res.json({ success: true, message: 'System is rebooting...' });
  } catch (error) {
    res.status(500).json({ error: 'Failed to reboot system', details: error.message });
  }
});

// System Management API (Hostname)
app.post('/api/system/hostname', (req, res) => {
  const { hostname } = req.body;
  if (!hostname) return res.status(400).json({ error: 'Hostname is required' });
  try {
    if (isLinux) {
      execSync(`hostnamectl set-hostname "${hostname}"`);
      fs.writeFileSync('/etc/hostname', hostname + '\n');
    }
    res.json({ success: true, message: 'Hostname updated successfully' });
  } catch (error) {
    res.status(500).json({ error: 'Failed to update hostname', details: error.message });
  }
});

// System Management API (Schedule Reboot via cron)
app.get('/api/system/schedule-reboot', (req, res) => {
  let enabled = false;
  let time = '04:00';
  try {
    if (isLinux) {
      const crontab = execSync('crontab -l 2>/dev/null || echo ""').toString();
      const match = crontab.match(/# SCADA_REBOOT\n(\d+) (\d+) \* \* \* \/sbin\/reboot/);
      if (match) {
        enabled = true;
        time = `${match[2].padStart(2,'0')}:${match[1].padStart(2,'0')}`;
      }
    } else {
      const cfgPath = path.join(__dirname, '..', 'config_data', 'schedule_reboot.json');
      if (fs.existsSync(cfgPath)) { const d = JSON.parse(fs.readFileSync(cfgPath)); enabled = d.enabled; time = d.time; }
    }
  } catch(e) {}
  res.json({ enabled, time });
});

app.post('/api/system/schedule-reboot', (req, res) => {
  const { enabled, time } = req.body;
  try {
    if (isLinux) {
      let crontab = '';
      try { crontab = execSync('crontab -l 2>/dev/null || echo ""').toString(); } catch(e) {}
      // Remove old SCADA_REBOOT lines
      crontab = crontab.split('\n').filter(l => !l.includes('# SCADA_REBOOT') && !l.match(/\d+ \d+ \* \* \* \/sbin\/reboot/)).join('\n');
      if (enabled && time) {
        const [hh, mm] = time.split(':');
        crontab += `\n# SCADA_REBOOT\n${mm} ${hh} * * * /sbin/reboot\n`;
      }
      const tmpFile = '/tmp/scada_cron';
      fs.writeFileSync(tmpFile, crontab.trim() + '\n');
      execSync(`crontab ${tmpFile}`);
      fs.unlinkSync(tmpFile);
    } else {
      const cfgPath = path.join(__dirname, '..', 'config_data', 'schedule_reboot.json');
      fs.writeFileSync(cfgPath, JSON.stringify({ enabled, time }, null, 2));
    }
    res.json({ success: true, message: 'Schedule reboot updated' });
  } catch(error) {
    res.status(500).json({ error: 'Failed to update schedule', details: error.message });
  }
});

// System Config Export (all config_data JSON files in a zip-like tar)
app.get('/api/system/config/export', (req, res) => {
  const configDir = path.join(__dirname, '..', 'config_data');
  const outFile = path.join(__dirname, '..', 'config_data', `scada_config_backup_${Date.now()}.tar.gz`);
  try {
    if (isLinux) {
      execSync(`tar -czf "${outFile}" -C "${path.dirname(configDir)}" config_data --exclude="*.tar.gz"`);
    } else {
      // On Windows dev: bundle all JSON files into a single JSON
      const files = fs.readdirSync(configDir).filter(f => f.endsWith('.json'));
      const bundle = {};
      files.forEach(f => {
        try { bundle[f] = JSON.parse(fs.readFileSync(path.join(configDir, f), 'utf-8')); } catch(e) {}
      });
      const devOut = outFile.replace('.tar.gz', '.json');
      fs.writeFileSync(devOut, JSON.stringify(bundle, null, 2));
      return res.download(devOut, 'scada_config_backup.json', () => { try { fs.unlinkSync(devOut); } catch(e) {} });
    }
    res.download(outFile, 'scada_config_backup.tar.gz', () => { try { fs.unlinkSync(outFile); } catch(e) {} });
  } catch(error) {
    console.error(error);
    res.status(500).json({ error: 'Export failed', details: error.message });
  }
});

// System Config Import (multipart upload)
const multer = require('multer');
const upload = multer({ dest: path.join(__dirname, '..', 'config_data', 'tmp_uploads') });

app.post('/api/system/config/import', upload.single('config_file'), (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
  const configDir = path.join(__dirname, '..', 'config_data');
  const uploadedPath = req.file.path;
  try {
    if (isLinux && req.file.originalname.endsWith('.tar.gz')) {
      execSync(`tar -xzf "${uploadedPath}" -C "${path.dirname(configDir)}"`);
    } else {
      // JSON bundle import (dev mode or if JSON file sent)
      const bundle = JSON.parse(fs.readFileSync(uploadedPath, 'utf-8'));
      Object.entries(bundle).forEach(([filename, data]) => {
        if (filename.endsWith('.json')) {
          fs.writeFileSync(path.join(configDir, filename), JSON.stringify(data, null, 2));
        }
      });
    }
    fs.unlinkSync(uploadedPath);
    res.json({ success: true, message: 'Configuration imported successfully. Please reboot for changes to take effect.' });
  } catch(error) {
    console.error(error);
    try { fs.unlinkSync(uploadedPath); } catch(e) {}
    res.status(500).json({ error: 'Import failed', details: error.message });
  }
});

// Global state to store previous CPU stat for accurate percentage calculation over time
let lastCpuStat = null;

app.get('/api/system/info', (req, res) => {
  const nets = os.networkInterfaces();
  const config = getNetworkConfig();
  const wanConfig = config.wan;
  const lanConfig = config.lan;
  const wlanConfig = config.wlan;

  const result = {
    name: os.hostname(),
    model: 'NanoPi R2S',
    version: '2.0.0',
    os: 'Linux (DietPi)',
    sn: '--',
    mac1: '--',
    mac2: '--',
    deviceTime: new Date().toLocaleString('sv').replace('T', ' '),
    operationTime: '--',
    cpu: 0,
    memory: 0,
    flash: 0,
    wan: wanConfig,
    lan: lanConfig,
    wlan: wlanConfig,
    eth0Status: 'Disconnected',
    eth1Status: 'Disconnected',
    wlan0Status: 'Disconnected'
  };

  // MAC addresses
  const getMac = (iface) => {
    let mac = '--';
    const n = nets[iface];
    if (n && n.length > 0) {
      mac = n[0].mac;
    }
    if ((!mac || mac === '--') && isLinux) {
      try { mac = fs.readFileSync(`/sys/class/net/${iface}/address`, 'utf-8').trim(); } catch(e) {}
    }
    return mac !== '--' ? mac.toUpperCase() : '--';
  };
  result.mac1 = getMac('eth0');
  result.mac2 = getMac('eth1');

  // Interface status
  if (nets['eth0']) {
    const ipv4 = nets['eth0'].find(n => n.family === 'IPv4' || n.family === 4);
    if (ipv4) {
      wanConfig.status = 'Connected';
      wanConfig.liveIp = ipv4.address;
      wanConfig.netmask = ipv4.netmask;
      wanConfig.mac = ipv4.mac;
    }
  }
  if (nets['eth1']) {
    const ipv4 = nets['eth1'].find(n => n.family === 'IPv4' || n.family === 4);
    if (ipv4) {
      lanConfig.status = 'Connected';
      lanConfig.liveIp = ipv4.address;
      lanConfig.netmask = ipv4.netmask;
      lanConfig.mac = ipv4.mac;
    }
  }
  if (nets['wlan0']) {
    const ipv4 = nets['wlan0'].find(n => n.family === 'IPv4' || n.family === 4);
    if (ipv4) {
      wlanConfig.status = 'Connected';
      wlanConfig.liveIp = ipv4.address;
      wlanConfig.netmask = ipv4.netmask;
      wlanConfig.mac = ipv4.mac;
    }
  }

  result.eth0Status = wanConfig.status;
  result.eth1Status = lanConfig.status;
  result.wlan0Status = wlanConfig.status;

  if (isLinux) {
    // CPU usage (sample /proc/stat compared to last API call)
    try {
      const currentStat = fs.readFileSync('/proc/stat', 'utf-8').split('\n')[0].trim().split(/\s+/).slice(1).map(Number);
      if (lastCpuStat) {
        const total1 = lastCpuStat.reduce((a, b) => a + b, 0);
        const idle1 = lastCpuStat[3];
        const total2 = currentStat.reduce((a, b) => a + b, 0);
        const idle2 = currentStat[3];
        const cpuUsage = Math.round(((total2 - total1 - (idle2 - idle1)) / Math.max(total2 - total1, 1)) * 100);
        result.cpu = Math.min(100, Math.max(0, cpuUsage));
      }
      lastCpuStat = currentStat;
    } catch(e) {}

    // Memory usage
    try {
      const meminfo = fs.readFileSync('/proc/meminfo', 'utf-8');
      const getMemVal = (key) => { const m = meminfo.match(new RegExp(`^${key}:\\s+(\\d+)`, 'm')); return m ? parseInt(m[1]) : 0; };
      const total = getMemVal('MemTotal');
      const available = getMemVal('MemAvailable');
      if (total > 0) result.memory = Math.round(((total - available) / total) * 100);
    } catch(e) {}

    // Flash usage (root partition)
    try {
      const df = execSync("df / --output=pcent | tail -1").toString().trim().replace('%', '');
      result.flash = parseInt(df) || 0;
    } catch(e) {}

    // Uptime (operation time)
    try {
      const upSec = parseFloat(fs.readFileSync('/proc/uptime', 'utf-8').split(' ')[0]);
      const h = Math.floor(upSec / 3600).toString().padStart(2, '0');
      const m = Math.floor((upSec % 3600) / 60).toString().padStart(2, '0');
      const s = Math.floor(upSec % 60).toString().padStart(2, '0');
      result.operationTime = `${h}:${m}:${s}`;
    } catch(e) {}

    // Hostname as device name
    try { result.name = execSync('hostname').toString().trim(); } catch(e) {}
  }

  res.json(result);
});

// Network Diagnostics API (Ping / Traceroute)
app.post('/api/network/diagnostics', (req, res) => {
  const { target, type } = req.body;
  if (!target || !['Ping', 'Traceroute'].includes(type)) return res.status(400).json({ error: 'Invalid parameters' });

  // Basic sanitization to prevent command injection
  if (!/^[a-zA-Z0-9.-]+$/.test(target)) return res.status(400).json({ error: 'Invalid target format' });

  let cmd = '';
  if (isLinux) {
    cmd = type === 'Ping' ? `ping -c 4 -W 2 ${target}` : `traceroute -m 20 -w 2 ${target}`;
  } else {
    cmd = type === 'Ping' ? `ping -n 4 -w 2000 ${target}` : `tracert -h 20 -w 2000 ${target}`;
  }

  require('child_process').exec(cmd, { timeout: 35000 }, (error, stdout, stderr) => {
    // We return stdout if available, otherwise stderr, otherwise error message
    res.json({ output: stdout || stderr || (error ? error.message : 'No output') });
  });
});

// Serve Frontend Static Files

const frontendDistPath = path.join(__dirname, 'public');
if (fs.existsSync(frontendDistPath)) {
  app.use(express.static(frontendDistPath));
  app.use((req, res) => {
    res.sendFile(path.join(frontendDistPath, 'index.html'));
  });
} else {
  app.get('/', (req, res) => {
    res.send("Backend is running. Frontend build not found in /public folder.");
  });
}

app.listen(PORT, '0.0.0.0', () => {
  console.log(`SCADA Gateway Backend running on http://0.0.0.0:${PORT}`);
});
